### ISSUE TITLE
Repo Cleanup

### ISSUE THREAD

**Issue by abcras** [mikkel080/BDSA-GitInsight#39]
This is a repeatable task
* Clean the repo of unused branches
* Clean the Insights Board of done tasks into an archive structure or open up a new week as per the current setup.

**Comment by Emilfranord** [comment]
All closed tickets in the Done track, have been archived. No branches that obviously need to be removed.

**Comment by Emilfranord** [comment]
The done list has been archived, and one unused branch has been deleted

**Comment by Emilfranord** [comment]
The "done" and "archived" trackes have been archived. One merged branch has been deleted.
