### ISSUE TITLE
Implement fork analysis to backend

### ISSUE THREAD

**Issue by mikkel080** [mikkel080/BDSA-GitInsight#68]
"When your GitInsight REST API receives a GET request with a GitHub repository identifier of the form `<github_user>/<repository_name>` or `<github_organization>/<repository_name>`, then besides the two already existing analyses of cloned Git repositories your application contacts the GitHub REST API to collect the number of forks of that repository."

**Comment by Emilfranord** [comment]
Se this link on the official GitHub docs
https://docs.github.com/en/rest/repos/forks#list-forks
This ticket / issue relates closely to #69
